preliminary linux support, -Dgootool.platform to override

diff --git a/dist_src/linux/bin/gootool b/dist_src/linux/bin/gootool
--- a/dist_src/linux/bin/gootool
+++ b/dist_src/linux/bin/gootool
@@ -2,13 +2,13 @@
 
 # Locate Java
 
-if [ ! -z "$JAVA_HOME" ]; then
-    JAVA=$JAVA_HOME/bin/java
+if [ ! -z "${JAVA_HOME}" ]; then
+    JAVA=${JAVA_HOME}/bin/java
 else
     JAVA=`which java`
 fi
 
-if [ ! -f "$JAVA" ]; then
+if [ ! -f "${JAVA}" ]; then
     echo "Can't locate java on your system" 1>&2
     echo "See http://goofans.com/gootool/troubleshooting/linux-java" 1>&2
     exit 1
@@ -16,10 +16,10 @@ fi
 
 # Check they have Java 1.6
 
-JAVA_VERSION=`$JAVA -version 2>&1 | awk '{ print substr($3, 2, 4); exit }'`
+JAVA_VERSION=`${JAVA} -version 2>&1 | awk '{ print substr($3, 2, 4); exit }'`
 
-if [ "$JAVA_VERSION" != "1.6." ]; then
-    echo "GooTool requires Java 1.6. You have Java $JAVA_VERSION" 1>&2
+if [ "${JAVA_VERSION}" != "1.5." -a "${JAVA_VERSION}" != "1.6." ]; then
+    echo "GooTool requires Java 1.5 or 1.6. You have Java ${JAVA_VERSION}" 1>&2
     echo "See http://goofans.com/gootool/troubleshooting/linux-java" 1>&2
     exit 1
 fi
@@ -33,10 +33,10 @@ function die()
 # Find the target of gootool symlink then locate gootool install dir
 
 GOOTOOL_EXE=`readlink -f $0` || die "Can't canonicalise $0"
-GOOTOOL_EXE_DIR=`dirname $GOOTOOL_EXE` || die "Can't dirname $GOOTOOL_EXE"
-GOOTOOL_DIR=`readlink -f $GOOTOOL_EXE_DIR/..` || die "Can't canonicalise $GOOTOOL_EXE_DIR/.."
+GOOTOOL_EXE_DIR=`dirname ${GOOTOOL_EXE}` || die "Can't dirname $GOOTOOL_EXE"
+GOOTOOL_DIR=`readlink -f ${GOOTOOL_EXE_DIR}/..` || die "Can't canonicalise ${GOOTOOL_EXE_DIR}/.."
 
-if [ ! -f "$GOOTOOL_DIR/lib/gootool.jar" ]; then
+if [ ! -f "${GOOTOOL_DIR}/lib/gootool.jar" ]; then
     echo "Can't find GooTool installation directory" 1>&2
     exit 1
 fi
@@ -45,11 +45,17 @@ fi
 
 CLASSPATH=""
 
-for i in $GOOTOOL_DIR/lib/*.jar; do
-    if [ ! -z "$CLASSPATH" ]; then
+for i in ${GOOTOOL_DIR}/lib/*.jar; do
+    if [ ! -z "${CLASSPATH}" ]; then
 	CLASSPATH=${CLASSPATH}:
     fi
     CLASSPATH=${CLASSPATH}$i
 done
 
-$JAVA -cp $CLASSPATH -Djava.util.logging.config.file=$GOOTOOL_DIR/etc/logger_properties.txt com.goofans.gootool.GooTool &
+JAVAARGS=""
+
+if [ ! -z "${GOOTOOL_PLATFORM}" ]; then
+    JAVAARGS="-Dgootool.platform=${GOOTOOL_PLATFORM}"
+fi
+
+$JAVA -cp ${CLASSPATH} -Djava.util.logging.config.file=$GOOTOOL_DIR/etc/logger_properties.txt ${JAVAARGS} com.goofans.gootool.GooTool $@ &
