changed directory detection for debian file layout

diff --git a/dist_src/linux/bin/gootool b/dist_src/linux/bin/gootool
--- a/dist_src/linux/bin/gootool
+++ b/dist_src/linux/bin/gootool
@@ -9,7 +9,7 @@ else
 fi
 
 if [ ! -f "${JAVA}" ]; then
-    echo "Can't locate java on your system" 1>&2
+    echo "Can't locate Java on your system" 1>&2
     echo "See http://goofans.com/gootool/troubleshooting/linux-java" 1>&2
     exit 1
 fi
@@ -30,27 +30,37 @@ function die()
     exit 1
 }
 
-# Find the target of gootool symlink then locate gootool install dir
+# Find the target of gootool symlink then locate gootool lib/etc directories
 
 GOOTOOL_EXE=`readlink -f $0` || die "Can't canonicalise $0"
 GOOTOOL_EXE_DIR=`dirname ${GOOTOOL_EXE}` || die "Can't dirname $GOOTOOL_EXE"
-GOOTOOL_DIR=`readlink -f ${GOOTOOL_EXE_DIR}/..` || die "Can't canonicalise ${GOOTOOL_EXE_DIR}/.."
 
-if [ ! -f "${GOOTOOL_DIR}/lib/gootool.jar" ]; then
-    echo "Can't find GooTool installation directory" 1>&2
-    exit 1
+if [ "${GOOTOOL_EXE_DIR}" = "/usr/bin" ]; then
+    GOOTOOL_LIB_DIR="/usr/share/gootool"
+    GOOTOOL_ETC_DIR="/etc/gootool"
+else
+    GOOTOOL_LIB_DIR=`readlink -f ${GOOTOOL_EXE_DIR}/../lib` || die "Can't canonicalise ${GOOTOOL_EXE_DIR}/../lib"
+    GOOTOOL_ETC_DIR=`readlink -f ${GOOTOOL_EXE_DIR}/../etc` || die "Can't canonicalise ${GOOTOOL_EXE_DIR}/../etc"
 fi
+
+# Verify we have found the right directories
+
+[ -f "${GOOTOOL_LIB_DIR}/gootool.jar" ] || die "Can't find GooTool library directory"
+
+[ -f "${GOOTOOL_ETC_DIR}/logger_properties.txt" ] || die "Can't find GooTool etc directory" 
 
 # Set up the classpath with all jars in lib dir
 
 CLASSPATH=""
 
-for i in ${GOOTOOL_DIR}/lib/*.jar; do
+for i in ${GOOTOOL_LIB_DIR}/*.jar; do
     if [ ! -z "${CLASSPATH}" ]; then
 	CLASSPATH=${CLASSPATH}:
     fi
     CLASSPATH=${CLASSPATH}$i
 done
+
+# Allow override of platform detection with env variable GOOTOOL_PLATFORM
 
 JAVAARGS=""
 
@@ -58,4 +68,6 @@ if [ ! -z "${GOOTOOL_PLATFORM}" ]; then
     JAVAARGS="-Dgootool.platform=${GOOTOOL_PLATFORM}"
 fi
 
-$JAVA -cp ${CLASSPATH} -Djava.util.logging.config.file=$GOOTOOL_DIR/etc/logger_properties.txt ${JAVAARGS} com.goofans.gootool.GooTool $@ &
+# Launch in background
+
+$JAVA -cp ${CLASSPATH} -Djava.util.logging.config.file=$GOOTOOL_ETC_DIR/logger_properties.txt ${JAVAARGS} com.goofans.gootool.GooTool $@ &
